var MeVPads = require("../dist/MeVPads.js");
var MeArticle = require("../src/me-article.js");
var Mag_1 = require("../dist/mag_1.js");
var React = require("react");
var ReactDOM = require("react-dom");
var EventEmitter = require("wolfy87-eventemitter");
var _article = new MeArticle(Mag_1);
var ee = new EventEmitter();
var pads = ReactDOM.render((<MeVPads bufferLen={5} article= {_article}></MeVPads>),document.getElementById("example1"));
console.log(_article);